# SPDX-License-Identifier: LGPL-2.1-or-later

[constants]
termux_prefix = '/data/data/com.termux/files/usr'
termux_etc = termux_prefix / 'etc'
termux_var = termux_prefix / 'var'
termux_run = termux_var / 'run'
termux_tmp = termux_prefix / 'tmp'
termux_bin = termux_prefix / 'bin'

[built-in options]
prefix = termux_prefix
sysconfdir = 'etc'
localstatedir = termux_var

[project options]
libc = 'bionic'
runstatedir = termux_run
tmpdir = termux_tmp
certificate-root = termux_etc / 'tls'
debug-shell = termux_bin / 'sh'
default-user-shell = termux_bin / 'sh'
user-path = termux_bin

# Termux does not provide a system instance of systemd, so keep the build
# focused on standalone tools and libraries.
binfmt = false
coredump = false
environment-d = false
firstboot = false
hibernate = false
hostnamed = false
hwdb = false
initrd = false
kernel-install = false
ldconfig = false
localed = false
logind = false
machined = false
mountfsd = false
networkd = false
nsresourced = false
nss-myhostname = false
nss-systemd = false
oomd = false
portabled = false
pstore = false
quotacheck = false
randomseed = false
resolve = false
rfkill = false
sysext = false
timedated = false
timesyncd = false
tpm = false
userdb = false
utmp = false
vconsole = false
xdg-autostart = false

bootloader = 'disabled'
homed = 'disabled'
imds = 'disabled'
importd = 'disabled'
nspawn = 'disabled'
nss-mymachines = 'disabled'
nss-resolve = 'disabled'
repart = 'disabled'
remote = 'disabled'
sysupdate = 'disabled'
ukify = 'disabled'
vmspawn = 'disabled'
